#!/usr/bin/env bash

if [[ "$1" = "-m" ]] || [[ "$1" = "-mac" ]]; then
    m1ddc display 1 set input 16
    m1ddc display 2 set input 15
    exit 0
elif [[ "$1" = "-w" ]] || [[ "$1" = "-windows" ]]; then
    m1ddc display 1 set input 15
    m1ddc display 2 set input 17
    exit 0
else
    exit 0
fi
