#!/usr/bin/env bash

arg_1=$(sed 's/^-//' <<< $1)

if [[ "$arg_1" = "m" ]] || [[ "$1" = "mac" ]]; then
    m1ddc display 1 set input 16
    m1ddc display 2 set input 15
    displayplacer "id:3 mode:115"
    exit 0
elif [[ "$arg_1" = "w" ]] || [[ "$1" = "windows" ]]; then
    m1ddc display 1 set input 15
    m1ddc display 2 set input 17
    exit 0
elif [[ "$arg_1" = "rr" ]] || [[ "$1" = "refreshrate" ]]; then
    displayplacer "id:3 mode:115"
    exit 0
else
    exit 0
fi
